export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const CHANGE_QUANTITY_OF_PRODUCT = "CHANGE_QUANTITY_OF_PRODUCT";
